apiVersion: v1
kind: Service
metadata:
  name: mongoose-entry-node-svc
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  ports:
    - name: data
      port: 1099
      targetPort: 1099
    - name: http
      port: 9999
      targetPort: 9999
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.pod.name }}-0
